# This is a basic workflow to help you get started with Actions

name: Build and deploy

# Controls when the workflow will run
on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  env:
    CI: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "build"
  build:
    # The type of runner that the job will run on
    name: build
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repos 
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: setup npm
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: install npm in cache
        uses: bahmutov/npm-install@v1
      # Runs a set of commands using the runners shell
      - name: Build 
        run: npm run build

      - name: upload build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu latest
    if: github.ref == 'refs/heads/master'
    
    steps:

    - name: download artifacts
      uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: &{{secrets.token}}
        pulish_dir: ./build
        
    
